import React from "react";
import * as _Builtin from "./_Builtin";
import { Navbar } from "./Navbar";
import { HeroBanner } from "./HeroBanner";
import { Footer } from "./Footer";

export function BuyPage({ as: _Component = _Builtin.Block }) {
  return (
    <_Component className="page-wrapper" tag="div">
      <Navbar />
      <_Builtin.Block className="main-wrapper" tag="div">
        <HeroBanner heading2Text="Buy" textSizeRegluarText="Creation" />
        <_Builtin.Block className="section-change-log" tag="div">
          <_Builtin.Block className="padding-global" tag="div">
            <_Builtin.Block className="container-large" tag="div">
              <_Builtin.Block className="padding-section-large buy" tag="div">
                <_Builtin.Block className="div-block-32" tag="div">
                  <_Builtin.Block
                    className="div-block-creation-main"
                    id="w-node-_288531a2-5f80-264b-2537-d07ba7507e5a-0fe3a9b9"
                    tag="div"
                  >
                    <_Builtin.Block
                      className="div-block-title-creation"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="div-block-description title"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6 image"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Image"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-image-creation"
                      tag="div"
                    >
                      <_Builtin.Image
                        className="image-creation"
                        loading="lazy"
                        width="auto"
                        height="auto"
                        alt=""
                        src="https://uploads-ssl.webflow.com/65ae6f1a145b7954f56170cc/65cddfd1b119f08fca8d8195_WhatsApp%20Image%202024-02-15%20at%2010.39.56%20(4).jpeg"
                      />
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-description-main"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="text-block-title-creation"
                        tag="div"
                      >
                        {"Title Creation"}
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="text-block-title-creation price"
                        tag="div"
                      >
                        {"5'000$"}
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className="div-block-creation-main"
                    id="w-node-_2f6c5c93-3688-6af2-188b-c3f2ee7f5411-0fe3a9b9"
                    tag="div"
                  >
                    <_Builtin.Block
                      className="div-block-title-creation"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="text-block-title-creation"
                        tag="div"
                      >
                        {"Title Creation"}
                      </_Builtin.Block>
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-image-creation"
                      tag="div"
                    >
                      <_Builtin.Image
                        className="image-creation"
                        loading="lazy"
                        width="auto"
                        height="auto"
                        alt=""
                        src="https://uploads-ssl.webflow.com/65ae6f1a145b7954f56170cc/65cddfd1433488a603f16bf3_WhatsApp%20Image%202024-02-15%20at%2010.39.56%20(5).jpeg"
                      />
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-description-main"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description image"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description animation"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description musique"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className="div-block-creation-main"
                    id="w-node-b257f64e-a8c9-dd63-40c2-3a407fc2b240-0fe3a9b9"
                    tag="div"
                  >
                    <_Builtin.Block
                      className="div-block-title-creation"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="text-block-title-creation"
                        tag="div"
                      >
                        {"Title Creation"}
                      </_Builtin.Block>
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-image-creation"
                      tag="div"
                    >
                      <_Builtin.Image
                        className="image-creation"
                        loading="lazy"
                        width="auto"
                        height="auto"
                        alt=""
                        src="https://uploads-ssl.webflow.com/65ae6f1a145b7954f56170cc/65cddfd18b5fae2613cbdad0_WhatsApp%20Image%202024-02-15%20at%2010.39.56%20(7).jpeg"
                      />
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-description-main"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description image"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description animation"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description musique"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className="div-block-creation-main"
                    id="w-node-_5ea9fa49-66cf-a509-7b4e-48170c7e4f19-0fe3a9b9"
                    tag="div"
                  >
                    <_Builtin.Block
                      className="div-block-title-creation"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="text-block-title-creation"
                        tag="div"
                      >
                        {"Title Creation"}
                      </_Builtin.Block>
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-image-creation"
                      tag="div"
                    >
                      <_Builtin.Image
                        className="image-creation"
                        loading="lazy"
                        width="auto"
                        height="auto"
                        alt=""
                        src="https://uploads-ssl.webflow.com/65ae6f1a145b7954f56170cc/65cddfd1c4a024842464870c_WhatsApp%20Image%202024-02-15%20at%2010.39.56%20(8).jpeg"
                      />
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-description-main"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description image"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description animation"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description musique"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className="div-block-creation-main"
                    id="w-node-_9a97f89a-93f6-9a68-ba6d-0245206cd6f2-0fe3a9b9"
                    tag="div"
                  >
                    <_Builtin.Block
                      className="div-block-title-creation"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="text-block-title-creation"
                        tag="div"
                      >
                        {"Title Creation"}
                      </_Builtin.Block>
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-image-creation"
                      tag="div"
                    >
                      <_Builtin.Image
                        className="image-creation"
                        loading="lazy"
                        width="auto"
                        height="auto"
                        alt=""
                        src="https://uploads-ssl.webflow.com/65ae6f1a145b7954f56170cc/65cddfd1e11fe41cf3ebd1d1_WhatsApp%20Image%202024-02-15%20at%2010.39.56%20(3).jpeg"
                      />
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-description-main"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description image"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description animation"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description musique"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className="div-block-creation-main"
                    id="w-node-_77b1b2f9-e623-10fd-70d4-d53118ae4197-0fe3a9b9"
                    tag="div"
                  >
                    <_Builtin.Block
                      className="div-block-title-creation"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="text-block-title-creation"
                        tag="div"
                      >
                        {"Title Creation"}
                      </_Builtin.Block>
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-image-creation"
                      tag="div"
                    >
                      <_Builtin.Image
                        className="image-creation"
                        loading="lazy"
                        width="auto"
                        height="auto"
                        alt=""
                        src="https://uploads-ssl.webflow.com/65ae6f1a145b7954f56170cc/65cddfd2726bbde7f75c64c1_WhatsApp%20Image%202024-02-15%20at%2010.39.56%20(6).jpeg"
                      />
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-description-main"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description image"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description animation"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description musique"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className="div-block-creation-main"
                    id="w-node-a5bd1a86-a63b-73a0-ab24-4ac5c3af1e8c-0fe3a9b9"
                    tag="div"
                  >
                    <_Builtin.Block
                      className="div-block-title-creation"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="text-block-title-creation"
                        tag="div"
                      >
                        {"Title Creation"}
                      </_Builtin.Block>
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-image-creation"
                      tag="div"
                    >
                      <_Builtin.Image
                        className="image-creation"
                        loading="lazy"
                        width="auto"
                        height="auto"
                        alt=""
                        src="https://uploads-ssl.webflow.com/65ae6f1a145b7954f56170cc/65cddfd2a5ea08b10b72ed85_WhatsApp%20Image%202024-02-15%20at%2010.39.56%20(2).jpeg"
                      />
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-description-main"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description image"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description animation"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description musique"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                  <_Builtin.Block
                    className="div-block-creation-main"
                    id="w-node-_8dc6faf2-2fa9-6ea7-3038-f967c82fc6db-0fe3a9b9"
                    tag="div"
                  >
                    <_Builtin.Block
                      className="div-block-title-creation"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="text-block-title-creation"
                        tag="div"
                      >
                        {"Title Creation"}
                      </_Builtin.Block>
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-image-creation"
                      tag="div"
                    >
                      <_Builtin.Image
                        className="image-creation"
                        loading="lazy"
                        width="auto"
                        height="auto"
                        alt=""
                        src="https://uploads-ssl.webflow.com/65ae6f1a145b7954f56170cc/65cddfd210da104c93aa8da6_WhatsApp%20Image%202024-02-15%20at%2010.39.56%20(9).jpeg"
                      />
                    </_Builtin.Block>
                    <_Builtin.Block
                      className="div-block-description-main"
                      tag="div"
                    >
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description image"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description animation"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                      <_Builtin.Block
                        className="div-block-description"
                        tag="div"
                      >
                        <_Builtin.HtmlEmbed
                          className="html-embed-6"
                          value="%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%228%22%20height%3D%228%22%20viewBox%3D%220%200%208%208%22%20fill%3D%22none%22%3E%0A%3Ccircle%20cx%3D%224%22%20cy%3D%224%22%20r%3D%224%22%20fill%3D%22currentColor%22%2F%3E%0A%3C%2Fsvg%3E"
                        />
                        <_Builtin.Block
                          className="text-block-description"
                          tag="div"
                        >
                          {"Description musique"}
                        </_Builtin.Block>
                      </_Builtin.Block>
                    </_Builtin.Block>
                  </_Builtin.Block>
                </_Builtin.Block>
              </_Builtin.Block>
            </_Builtin.Block>
          </_Builtin.Block>
        </_Builtin.Block>
      </_Builtin.Block>
      <Footer />
    </_Component>
  );
}
